In [1]:
import xarray as xr
import cftime
import numpy as np

fp = "/beegfs/CMIP6/jdpaul3/cmip6_regrid_for_rasdaman_test/cmip6_regrid_mon_ensemble.nc"

In [2]:
ds = xr.open_dataset(fp, decode_cf=True)
ds

<xarray.Dataset> Size: 126GB
Dimensions:      (model: 14, scenario: 5, time: 1812, lat: 43, lon: 288)
Coordinates:
  * model        (model) int64 112B 0 1 2 3 4 5 6 7 8 9 10 11 12 13
  * scenario     (scenario) int64 40B 0 1 2 3 4
  * lat          (lat) float64 344B 90.0 89.06 88.12 87.17 ... 52.3 51.36 50.42
  * lon          (lon) float64 2kB -180.0 -178.8 -177.5 ... 176.2 177.5 178.8
  * time         (time) object 14kB 1950-01-15 12:00:00 ... 2100-12-15 12:00:00
Data variables: (12/19)
    clt          (model, scenario, time, lat, lon) float64 13GB ...
    evspsbl      (model, scenario, time, lat, lon) float32 6GB ...
    hfls         (model, scenario, time, lat, lon) float32 6GB ...
    hfss         (model, scenario, time, lat, lon) float32 6GB ...
    pr           (model, scenario, time, lat, lon) float32 6GB ...
    prsn         (model, scenario, time, lat, lon) float32 6GB ...
    ...           ...
    tasmax       (model, scenario, time, lat, lon) float32 6GB ...
    tasmin       (model, scenario, time, lat, lon) float32 6GB ...
    ts           (model, scenario, time, lat, lon) float32 6GB ...
    uas          (model, scenario, time, lat, lon) float32 6GB ...
    vas          (model, scenario, time, lat, lon) float32 6GB ...
    spatial_ref  int64 8B ...
Attributes:
    Conventions:  CF-1.8
    title:        CMIP6 Monthly Data on a Common Grid with Multi-Model Ensemb...
    description:  Monthly data from 13 CMIP6 models on a common grid, includi...
    institution:  Scenarios Network for Alaska and Arctic Planning, Universit...
    source:       CMIP6 model output
    contact:      uaf-snap-data-tools@alaska.edu
    url:          https://uaf-snap.org/

In [3]:
# test each variable to make sure the ensemble mean is calculated correctly

# historical data

lat = 65
lon = -142
time = "2000-01-15"


scenario = 0
models = slice(0, 13)  # first 13 models


for var in list(ds.data_vars):
    if var != "spatial_ref":
        print(f"Variable: {var}")

        print("Original Dataset Values:")
        values = (
            ds[var]
            .sel(
                lat=lat,
                lon=lon,
                method="nearest",
            )
            .sel(time=time, scenario=scenario, model=models)
            .values
        )

        print(values)
        print("\n Calculated Ensemble Mean:")
        print(np.nanmean(values))

        print("Dataset Ensemble Mean:")
        print(
            ds[var]
            .sel(
                lat=lat,
                lon=lon,
                method="nearest",
            )
            .sel(time=time, scenario=scenario, model=13)
            .values
        )

        print("\n\n")

Variable: clt
Original Dataset Values:
[[84.]
 [84.]
 [93.]
 [87.]
 [90.]
 [93.]
 [96.]
 [97.]
 [69.]
 [63.]
 [85.]
 [73.]
 [88.]
 [85.]]

 Calculated Ensemble Mean:
84.78571428571429
Dataset Ensemble Mean:
[85.]



Variable: evspsbl
Original Dataset Values:
[[-8.0136459e-07]
 [-5.1908472e-07]
 [-7.8565273e-07]
 [-2.4567325e-07]
 [ 1.7288687e-06]
 [-2.0015928e-07]
 [-2.4867447e-07]
 [ 6.4609040e-08]
 [ 4.4354474e-07]
 [-4.4103714e-07]
 [ 4.4930988e-07]
 [-1.6630395e-07]
 [-4.7408409e-07]
 [-9.1977057e-08]]

 Calculated Ensemble Mean:
-9.197707e-08
Dataset Ensemble Mean:
[-9.197706e-08]



Variable: hfls
Original Dataset Values:


[[-2.0768504 ]
 [-1.4162908 ]
 [-1.9648086 ]
 [-0.666201  ]
 [ 4.322172  ]
 [-0.56746614]
 [-0.7049919 ]
 [ 0.18316348]
 [ 1.1088618 ]
 [-1.2336146 ]
 [ 1.2762977 ]
 [-0.4220986 ]
 [-1.2313712 ]
 [-0.26101524]]

 Calculated Ensemble Mean:
-0.26101524
Dataset Ensemble Mean:
[-0.26101524]



Variable: hfss
Original Dataset Values:
[[-10.327375 ]
 [-11.522432 ]
 [ -8.958679 ]
 [ -6.954862 ]
 [-25.400227 ]
 [  0.9479265]
 [ -2.603221 ]
 [ -4.72951  ]
 [-22.985388 ]
 [ -8.682584 ]
 [-16.209604 ]
 [-15.121722 ]
 [-15.593716 ]
 [-11.395493 ]]

 Calculated Ensemble Mean:
-11.395493
Dataset Ensemble Mean:
[-11.395493]



Variable: pr
Original Dataset Values:
[[30. ]
 [27.7]
 [21.2]
 [46.1]
 [42.4]
 [61. ]
 [28.6]
 [36.8]
 [42.7]
 [45.2]
 [40.7]
 [61.6]
 [28.6]
 [39.4]]

 Calculated Ensemble Mean:
39.428577
Dataset Ensemble Mean:
[39.4]



Variable: prsn
Original Dataset Values:
[[30. ]
 [27.5]
 [20.5]
 [46. ]
 [35.8]
 [60.9]
 [28.4]
 [36.5]
 [39.8]
 [44.6]
 [40.7]
 [59. ]
 [28.3]
 [38.3]]

 Cal

/tmp/ipykernel_178027/2310239202.py:32: RuntimeWarning: Mean of empty slice
  print(np.nanmean(values))


[[145.2]
 [107.6]
 [ 97.7]
 [145. ]
 [ 82.9]
 [ 69.3]
 [ 41.7]
 [  nan]
 [137.2]
 [156.1]
 [119.8]
 [168.3]
 [124.2]
 [116.3]]

 Calculated Ensemble Mean:
116.25386
Dataset Ensemble Mean:
[116.3]



Variable: tas
Original Dataset Values:
[[-20.4]
 [-20.1]
 [-20.1]
 [-23.3]
 [-13.5]
 [-30.5]
 [-22.1]
 [-17.5]
 [-15.8]
 [-24.7]
 [-14.9]
 [-29.8]
 [-18.6]
 [-20.9]]

 Calculated Ensemble Mean:
-20.871428
Dataset Ensemble Mean:
[-20.9]



Variable: tasmax
Original Dataset Values:
[[  nan]
 [-14.8]
 [  nan]
 [-20.7]
 [-10.8]
 [-27. ]
 [-18.4]
 [-14. ]
 [-12.5]
 [-19.6]
 [-11. ]
 [  nan]
 [  nan]
 [-16.5]]

 Calculated Ensemble Mean:
-16.53
Dataset Ensemble Mean:
[-16.5]



Variable: tasmin
Original Dataset Values:
[[  nan]
 [-24.7]
 [  nan]
 [-25.7]
 [-16. ]
 [-33.9]
 [-26.2]
 [-21.4]
 [-19.2]
 [-29.4]
 [-18.1]
 [  nan]
 [  nan]
 [-23.8]]

 Calculated Ensemble Mean:
-23.84
Dataset Ensemble Mean:
[-23.8]



Variable: ts
Original Dataset Values:
[[252.2]
 [250.6]
 [252.1]
 [261.9]
 [259.5]
 [2

In [4]:
# test each variable to make sure the ensemble mean is calculated correctly

# projected data

lat = 65
lon = -142
time = "2050-01-15"


scenario = 1
models = slice(0, 13)  # first 13 models


for var in list(ds.data_vars):
    if var != "spatial_ref":
        print(f"Variable: {var}")

        print("Original Dataset Values:")
        values = (
            ds[var]
            .sel(
                lat=lat,
                lon=lon,
                method="nearest",
            )
            .sel(time=time, scenario=scenario, model=models)
            .values
        )

        print(values)
        print("\n Calculated Ensemble Mean:")
        print(np.nanmean(values))

        print("Dataset Ensemble Mean:")
        print(
            ds[var]
            .sel(
                lat=lat,
                lon=lon,
                method="nearest",
            )
            .sel(time=time, scenario=scenario, model=13)
            .values
        )

        print("\n\n")

Variable: clt
Original Dataset Values:
[[89.]
 [80.]
 [nan]
 [86.]
 [92.]
 [93.]
 [92.]
 [94.]
 [62.]
 [63.]
 [80.]
 [82.]
 [93.]
 [84.]]

 Calculated Ensemble Mean:
83.84615384615384
Dataset Ensemble Mean:
[84.]



Variable: evspsbl
Original Dataset Values:


[[-1.4496624e-07]
 [-4.6953272e-07]
 [           nan]
 [-3.4780524e-07]
 [ 1.8423696e-06]
 [ 1.0234568e-07]
 [-1.9948602e-07]
 [-8.6433111e-08]
 [-3.3505276e-07]
 [ 6.8707163e-07]
 [ 5.9280660e-07]
 [-6.0456387e-07]
 [-3.7781973e-07]
 [ 5.4911158e-08]]

 Calculated Ensemble Mean:
5.4911155e-08
Dataset Ensemble Mean:
[5.491116e-08]



Variable: hfls
Original Dataset Values:
[[-0.35044044]
 [-1.2797098 ]
 [        nan]
 [-0.9284081 ]
 [ 4.6059237 ]
 [ 0.29015887]
 [-0.5655577 ]
 [-0.24505429]
 [-0.8376319 ]
 [ 1.927391  ]
 [ 1.6839334 ]
 [-1.6325666 ]
 [-0.97227407]
 [ 0.14131366]]

 Calculated Ensemble Mean:
0.14131366
Dataset Ensemble Mean:
[0.14131366]



Variable: hfss
Original Dataset Values:
[[-18.146208 ]
 [-13.254973 ]
 [        nan]
 [-10.666106 ]
 [-16.956877 ]
 [ -6.221248 ]
 [ -3.6618059]
 [ -8.777778 ]
 [-22.02843  ]
 [-26.050032 ]
 [-18.344864 ]
 [-14.748734 ]
 [-13.619531 ]
 [-14.373049 ]]

 Calculated Ensemble Mean:
-14.373049
Dataset Ensemble Mean:
[-14.373049]



Variab

/tmp/ipykernel_178027/3768759034.py:32: RuntimeWarning: Mean of empty slice
  print(np.nanmean(values))


[[136.2]
 [100.9]
 [  nan]
 [127.5]
 [105.7]
 [ 24.8]
 [ 51.5]
 [  nan]
 [ 70.9]
 [144.6]
 [158.9]
 [239.5]
 [ 91.2]
 [113.8]]

 Calculated Ensemble Mean:
113.791664
Dataset Ensemble Mean:
[113.8]



Variable: tas
Original Dataset Values:
[[-12.9]
 [-23.3]
 [  nan]
 [-25.4]
 [-17.1]
 [-20. ]
 [-25. ]
 [-31.7]
 [-17. ]
 [-20.9]
 [-22.8]
 [-15.3]
 [-16.1]
 [-20.6]]

 Calculated Ensemble Mean:
-20.623077
Dataset Ensemble Mean:
[-20.6]



Variable: tasmax
Original Dataset Values:
[[  0.1]
 [-18.4]
 [  nan]
 [-22.9]
 [-12.4]
 [-16.6]
 [-20.8]
 [-29.2]
 [-14.3]
 [-17.1]
 [-18.1]
 [  nan]
 [  nan]
 [-17. ]]

 Calculated Ensemble Mean:
-16.972729
Dataset Ensemble Mean:
[-17.]



Variable: tasmin
Original Dataset Values:
[[-24.4]
 [-28. ]
 [  nan]
 [-27.3]
 [-21.6]
 [-23.5]
 [-28.6]
 [-33.5]
 [-19.9]
 [-24.4]
 [-26.5]
 [  nan]
 [  nan]
 [-25.8]]

 Calculated Ensemble Mean:
-25.772724
Dataset Ensemble Mean:
[-25.8]



Variable: ts
Original Dataset Values:
[[259.4]
 [246.9]
 [  nan]
 [264.8]
 [25